### ISSUE TITLE
"#comment" nodes and number of children

### ISSUE THREAD

**Issue by muffato** [anujk14/XML-To-Blockly#5]
"#comment" nodes are currently kept in the document and ignored since 95966e7dde9ed1ec981ed0aef71ce3d91a55a667
The problem is that there are still included in the number of children of their parents, potentially fooling tests like parser.js#L143
They should either be removed like "#text" nodes are, or added as comments to the blocks

**Comment by muffato** [comment]
We cannot tell whether XML comments are meant to be displayed or not
https://github.com/anujk14/XML-To-Blockly/blob/gh-pages/examples/LRG.rng#L20 could be displayed
https://github.com/anujk14/XML-To-Blockly/blob/gh-pages/examples/LRG.rng#L64 shouldn't

Let's remove them all, and we'll use "blockly:comment" attributes or tags to define those that need to displayed

**Comment by muffato** [comment]
I'm working on this and will commit the change soon

**Comment by anujk14** [comment]
Oh no. I'm really sorry I'd completely forgotten about this bug.

**Comment by muffato** [comment]
no worries, it's simple enough I can do it :)
