### ISSUE TITLE
Independent <text/> nodes not appearing in some cases

### ISSUE THREAD

**Issue by anujk14** [anujk14/XML-To-Blockly#7]
I don't know we ever encounter a schema like this or not, but the following structure produces an empty oneOrMore block:

oneOrMore -> text/ -> /oneOrMore

Would this be allowed?

**Comment by muffato** [comment]
Sorry I'm only seeing this now, if you mean
```xml
    <start>
        <oneOrMore>
            <text/>
        </oneOrMore>
    </start>
```
yes this is valid

**Comment by anujk14** [comment]
Pushed a commit with the updated version that has resolved this bug. @muffato would you like to check once before marking it as resolved?

**Comment by muffato** [comment]
Unfortunately this is not working any more :(

**Comment by anujk14** [comment]
Is there a particular example where this is causing a problem?

**Comment by muffato** [comment]
The one in https://github.com/anujk14/XML-To-Blockly/issues/7#issuecomment-226633396 :)

**Comment by anujk14** [comment]
Oh, I think it's because of the missing <grammar> blocks ! 
This seems to work : 
```<grammar>
    <start>
        <oneOrMore>
            <text/>
        </oneOrMore>
    </start>
</grammar>```

**Comment by muffato** [comment]
Yes ... That was stupid of me !
